name: smartphone_review
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserratt.ttf


